# Generated by Django 3.1.2 on 2020-10-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('regular_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product_rating', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product_review', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('categories', models.CharField(max_length=400)),
            ],
        ),
    ]
