# Generated by Django 3.1.2 on 2020-10-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20201017_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
