# Generated by Django 3.1.2 on 2020-10-18 09:30

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('order_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('userid', models.CharField(max_length=20)),
                ('product_details', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
