# Generated by Django 3.1.2 on 2020-10-18 09:41

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_auto_20201018_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_details',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
