# Generated by Django 3.1.2 on 2020-10-18 10:16

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmode',
            name='details',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
