# Generated by Django 3.1.2 on 2020-10-18 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_paymentmode_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transactionid',
        ),
    ]
